"use client";
import { useMemo, useState, useTransition } from "react";
import { CheckCircle2, ClipboardPlus, Copy, Download, FileUp, Plus, RotateCcw, Save, Search, Trash2, XCircle } from "lucide-react";
import { saveSmartEntries, decideSmartEntry, retrySmartEntry } from "@/app/(app)/smart-entry/actions";

const TYPE_LABELS={customer:"Customer",delivery:"Delivery",payment:"Payment",expense:"Expense",bottle:"Bottle Issue / Return",inventory_purchase:"Inventory Purchase",employee_salary:"Employee / Salary",invoice_adjustment:"Invoice / Adjustment",complaint_feedback:"Complaint / Feedback"};
const today=()=>new Date().toISOString().slice(0,10);
const defaults=(type)=>({client_key:crypto.randomUUID(),delivery_date:today(),payment_date:today(),expense_date:today(),txn_date:today(),date:today(),method:"Cash",kind:"complaint",direction:"debit",record_kind:"adjustment",returned_qty:0,cash_collected:0});
const FIELD_MAP={
 customer:[["name","Customer name","text"],["phone","Mobile number","tel"],["address","Address","text"],["customer_type","Type","text"],["payment_frequency","Payment frequency","text"],["rate","Rate","number"]],
 delivery:[["customer_id","Customer","customer"],["delivery_date","Date","date"],["product_id","Bottle size","product"],["delivered_qty","Delivered","number"],["returned_qty","Empty returned","number"],["cash_collected","Cash collected","number"],["override_rate","Override rate","number"],["override_reason","Override reason","text"]],
 payment:[["customer_id","Customer","customer"],["amount","Amount","number"],["payment_date","Date","date"],["method","Mode","method"],["reference","Reference","text"],["notes","Notes","text"]],
 expense:[["category","Category","category"],["expense_date","Date","date"],["amount","Amount","number"],["method","Mode","method"],["description","Description","text"],["receipt_reference","Receipt ref","text"]],
 bottle:[["customer_id","Customer","customer"],["txn_date","Date","date"],["product_id","Bottle size","product"],["issued","Issued","number"],["returned","Returned","number"],["damaged","Damaged","number"],["lost","Lost","number"],["adjustment","Adjustment","number"],["reason","Reason","text"]],
 inventory_purchase:[["supplier","Supplier","text"],["item","Item","text"],["date","Date","date"],["qty","Quantity","number"],["rate","Rate","number"]],
 employee_salary:[["employee_id","Employee","employee"],["date","Date","date"],["amount","Amount","number"],["reason","Reason","text"]],
 invoice_adjustment:[["customer_id","Customer","customer"],["record_kind","Record","recordkind"],["date","Date","date"],["amount","Adjustment amount","number"],["direction","Debit / Credit","direction"],["reason","Reason","text"]],
 complaint_feedback:[["customer_id","Customer","customer"],["kind","Type","kind"],["description","Details","text"],["rating","Rating 1–5","number"]],
};

function Field({field,row,index,error,onChange,options}){
 const [key,label,kind]=field; const cls=`w-full min-w-[135px] rounded-xl border px-3 py-2.5 text-sm bg-card outline-none ${error?"border-red-500 bg-red-50":"border-line focus:border-aqua"}`;
 let input;
 if(kind==="customer") input=<select className={cls} value={row[key]||""} onChange={e=>onChange(index,key,e.target.value)}><option value="">Search / select customer</option>{options.customers.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name} · {c.mobile}</option>)}</select>;
 else if(kind==="product") input=<select className={cls} value={row[key]||""} onChange={e=>onChange(index,key,e.target.value)}><option value="">Select size</option>{options.products.map(p=><option key={p.id} value={p.id}>{p.size_label||p.name}</option>)}</select>;
 else if(kind==="category") input=<select className={cls} value={row[key]||""} onChange={e=>onChange(index,key,e.target.value)}><option value="">Select category</option>{options.categories.map(p=><option key={p.id} value={p.name}>{p.name}</option>)}</select>;
 else if(kind==="employee") input=<select className={cls} value={row[key]||""} onChange={e=>onChange(index,key,e.target.value)}><option value="">Select employee</option>{options.employees.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select>;
 else if(kind==="method") input=<select className={cls} value={row[key]||"Cash"} onChange={e=>onChange(index,key,e.target.value)}><option>Cash</option><option>Bank Transfer</option><option>JazzCash</option><option>Easypaisa</option></select>;
 else if(kind==="kind") input=<select className={cls} value={row[key]||"complaint"} onChange={e=>onChange(index,key,e.target.value)}><option value="complaint">Complaint</option><option value="feedback">Feedback</option></select>;
 else if(kind==="direction") input=<select className={cls} value={row[key]||"debit"} onChange={e=>onChange(index,key,e.target.value)}><option value="debit">Debit</option><option value="credit">Credit</option></select>;
 else if(kind==="recordkind") input=<select className={cls} value={row[key]||"adjustment"} onChange={e=>onChange(index,key,e.target.value)}><option value="adjustment">Adjustment</option><option value="invoice">Invoice</option></select>;
 else input=<input className={cls} type={kind} value={row[key]??""} onChange={e=>onChange(index,key,e.target.value)} placeholder={label} />;
 return <label className="block"><span className="mb-1 block text-[11px] font-bold uppercase tracking-wide text-slate">{label}</span>{input}{error&&<span className="mt-1 block text-xs font-semibold text-red-600">{error}</span>}</label>;
}

export default function SmartEntryWorkspace({customers,products,categories,employees,initialEntries,rules}){
 const [type,setType]=useState("delivery"),[mode,setMode]=useState("single"),[rows,setRows]=useState([defaults("delivery")]),[result,setResult]=useState(null),[entries,setEntries]=useState(initialEntries),[pending,start]=useTransition(),[query,setQuery]=useState("");
 const options={customers,products,categories,employees}; const fields=FIELD_MAP[type];
 const change=(i,k,v)=>setRows(old=>old.map((r,x)=>x===i?{...r,[k]:v}:r));
 const switchType=t=>{setType(t);setRows([defaults(t)]);setResult(null)};
 const submit=intent=>start(async()=>{const res=await saveSmartEntries(type,rows,intent,mode==="bulk"?"bulk":"single");setResult(res);if(res?.results)setRows(old=>old.map((r,i)=>({...r,_errors:res.results.find(x=>x.index===i)?.errors||{},_status:res.results.find(x=>x.index===i)?.status,_warnings:res.results.find(x=>x.index===i)?.warnings||[]})));});
 const importFile=async e=>{const file=e.target.files?.[0];if(!file)return;const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const data=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""}).slice(0,100);setRows(data.map(r=>({...defaults(type),...Object.fromEntries(Object.entries(r).map(([k,v])=>[k.toLowerCase().trim().replaceAll(" ","_"),v instanceof Date?v.toISOString().slice(0,10):v]))})));setMode("bulk");};
 const downloadErrors=async()=>{const bad=rows.filter(r=>r._status==="failed");if(!bad.length)return;const XLSX=await import("xlsx");const ws=XLSX.utils.json_to_sheet(bad.map(({_errors,_status,_warnings,...r})=>({...r,Errors:Object.values(_errors||{}).join("; ")})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Error Rows");XLSX.writeFile(wb,"smart-entry-error-rows.xlsx")};
 const filtered=useMemo(()=>entries.filter(e=>[e.entry_no,e.entry_type,e.status,e.payload?.name].join(" ").toLowerCase().includes(query.toLowerCase())),[entries,query]);
 const act=(id,decision)=>start(async()=>{const reason=decision==="reject"?prompt("Rejection reason (required):"):"Approved";if(decision==="reject"&&!reason)return;const r=await decideSmartEntry(id,decision,reason);if(r?.error)alert(r.error);else setEntries(v=>v.map(e=>e.id===id?{...e,status:decision==="approve"?"approved":"rejected",decision_reason:reason}:e))});
 return <div className="space-y-5">
  <section className="overflow-hidden rounded-[26px] bg-gradient-to-br from-navy via-[#075E55] to-aqua p-5 text-white shadow-xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-aquaSoft"><ClipboardPlus size={17}/>Central transaction desk</div><h1 className="font-display text-3xl font-semibold">Smart Entry</h1><p className="mt-2 max-w-2xl text-sm text-white/75">One safe place for daily customer, delivery, payment, expense, bottle and accounting records.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-sm"><b>{rules.filter(r=>r.requires_approval).length}</b> entry types require approval</div></div></section>
  <section className="rounded-2xl border border-line bg-card p-4 shadow-sm"><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{Object.entries(TYPE_LABELS).map(([k,v])=><button type="button" key={k} onClick={()=>switchType(k)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${type===k?"bg-navy text-white":"bg-foam text-slate"}`}>{v}</button>)}</div><div className="mb-4 flex flex-wrap items-center gap-2"><button type="button" onClick={()=>setMode("single")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${mode==="single"?"bg-aqua text-white":"border border-line"}`}>Single Entry</button><button type="button" onClick={()=>setMode("bulk")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${mode==="bulk"?"bg-aqua text-white":"border border-line"}`}>Bulk Entry</button>{mode==="bulk"&&<label className="ml-auto flex cursor-pointer items-center gap-2 rounded-xl border border-line px-3 py-2 text-sm font-semibold"><FileUp size={16}/>Import Excel/CSV<input className="hidden" type="file" accept=".xlsx,.xls,.csv" onChange={importFile}/></label>}</div>
   <div className={mode==="bulk"?"overflow-x-auto":""}><div className={mode==="single"?"grid gap-3 md:grid-cols-2 xl:grid-cols-4":"min-w-[1050px] space-y-3"}>{rows.map((row,i)=><div key={row.client_key} className={mode==="bulk"?"grid grid-cols-[45px_repeat(4,minmax(150px,1fr))_90px] gap-2 rounded-2xl border border-line p-3":"contents"}>{mode==="bulk"&&<div className="pt-8 text-center font-mono text-xs text-slate">{i+1}</div>}{fields.map(f=><Field key={f[0]} field={f} row={row} index={i} error={row._errors?.[f[0]]} onChange={change} options={options}/>)}{mode==="bulk"&&<div className="flex items-center gap-1 pt-6"><button title="Duplicate row" type="button" onClick={()=>setRows(v=>[...v.slice(0,i+1),{...row,client_key:crypto.randomUUID(),_errors:{},_status:null},...v.slice(i+1)])} className="p-2"><Copy size={16}/></button><button title="Clear row" type="button" onClick={()=>setRows(v=>v.map((r,x)=>x===i?defaults(type):r))} className="p-2"><RotateCcw size={16}/></button><button title="Remove unsaved row" type="button" onClick={()=>setRows(v=>v.length>1?v.filter((_,x)=>x!==i):v)} className="p-2 text-red-600"><Trash2 size={16}/></button></div>}{row._warnings?.length>0&&<div className="col-span-full rounded-lg bg-amber-50 p-2 text-xs font-semibold text-amber-700">{row._warnings.join(" ")}</div>}</div>)}</div></div>
   <div className="mt-4 flex flex-wrap gap-2">{mode==="bulk"&&<button type="button" onClick={()=>setRows(v=>v.length<100?[...v,defaults(type)]:v)} className="flex items-center gap-2 rounded-xl border border-line px-4 py-2 text-sm font-bold"><Plus size={16}/>Add Row</button>}<button disabled={pending} type="button" onClick={()=>submit("draft")} className="flex items-center gap-2 rounded-xl border border-line px-4 py-2 text-sm font-bold"><Save size={16}/>Save Draft</button><button disabled={pending} type="button" onClick={()=>submit("submit")} className="flex items-center gap-2 rounded-xl bg-navy px-5 py-2 text-sm font-bold text-white">{pending?"Processing…":"Submit / Save All Valid"}</button>{rows.some(r=>r._status==="failed")&&<button type="button" onClick={downloadErrors} className="flex items-center gap-2 rounded-xl bg-red-50 px-4 py-2 text-sm font-bold text-red-700"><Download size={16}/>Download Error Rows</button>}</div>
  </section>
  {result&&<section className="grid grid-cols-2 gap-3 md:grid-cols-5">{[["Total Rows",result.total],["Successfully Saved",result.saved],["Failed",result.failed],["Duplicate Warnings",result.duplicates],["Pending Approval",result.pending]].map(([l,v])=><div key={l} className="rounded-2xl border border-line bg-card p-4"><div className="text-xs font-bold uppercase text-slate">{l}</div><div className="mt-1 text-2xl font-bold">{v||0}</div></div>)}</section>}
  <section className="rounded-2xl border border-line bg-card p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-display text-xl font-semibold">Entry Queue & Audit</h2><p className="text-xs text-slate">Draft, pending, rejected and failed rows never affect official balances.</p></div><label className="relative"><Search className="absolute left-3 top-2.5 text-slate" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search entry…" className="rounded-xl border border-line py-2 pl-9 pr-3 text-sm"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="sticky top-0 bg-foam"><tr>{["Reference","Type","Status","Entered by","Date","Result / Action"].map(h=><th key={h} className="p-3 text-left text-xs uppercase text-slate">{h}</th>)}</tr></thead><tbody>{filtered.map(e=><tr key={e.id} className="border-t border-line"><td className="p-3 font-mono font-semibold">{e.entry_no}</td><td className="p-3">{TYPE_LABELS[e.entry_type]}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${e.status==="approved"?"bg-green-100 text-green-700":e.status==="failed"||e.status==="rejected"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{e.status.replaceAll("_"," ")}</span></td><td className="p-3">{e.profiles?.full_name||"—"}</td><td className="p-3">{new Date(e.created_at).toLocaleDateString("en-PK")}</td><td className="p-3">{e.status==="pending_approval"?<div className="flex gap-2"><button onClick={()=>act(e.id,"approve")} className="flex items-center gap-1 text-green-700"><CheckCircle2 size={16}/>Approve</button><button onClick={()=>act(e.id,"reject")} className="flex items-center gap-1 text-red-600"><XCircle size={16}/>Reject</button></div>:<span className="text-xs text-slate">{Object.values(e.validation_errors||{}).join(" · ")||e.decision_reason||"Posted"}</span>}</td></tr>)}</tbody></table></div></section>
 </div>
}
