do $$
declare v_biz_id uuid;
begin
  select id into v_biz_id from businesses where name = 'Evergreen Water';
  if v_biz_id is null then raise exception 'Evergreen Water business row not found'; end if;

  update customers set business_id = v_biz_id where business_id is null;
  update customer_prices set business_id = v_biz_id where business_id is null;
  update customer_complaints set business_id = v_biz_id where business_id is null;
  update customer_ledger_entries set business_id = v_biz_id where business_id is null;
  update deliveries set business_id = v_biz_id where business_id is null;
  update delivery_items set business_id = v_biz_id where business_id is null;
  update bottle_transactions set business_id = v_biz_id where business_id is null;
  update bottle_reconciliations set business_id = v_biz_id where business_id is null;
  update inventory_items set business_id = v_biz_id where business_id is null;
  update inventory_movements set business_id = v_biz_id where business_id is null;
  update invoices set business_id = v_biz_id where business_id is null;
  update invoice_items set business_id = v_biz_id where business_id is null;
  update orders set business_id = v_biz_id where business_id is null;
  update order_items set business_id = v_biz_id where business_id is null;
  update payments set business_id = v_biz_id where business_id is null;
  update expenses set business_id = v_biz_id where business_id is null;
  update expense_categories set business_id = v_biz_id where business_id is null;
  update expense_category_account_map set business_id = v_biz_id where business_id is null;
  update products set business_id = v_biz_id where business_id is null;
  update product_prices set business_id = v_biz_id where business_id is null;
  update profiles set business_id = v_biz_id where business_id is null;
  update vehicles set business_id = v_biz_id where business_id is null;
  update vehicle_fuel_logs set business_id = v_biz_id where business_id is null;
  update vehicle_maintenance_logs set business_id = v_biz_id where business_id is null;
  update routes set business_id = v_biz_id where business_id is null;
  update zones set business_id = v_biz_id where business_id is null;
  update employee_advances set business_id = v_biz_id where business_id is null;
  update employee_attendance set business_id = v_biz_id where business_id is null;
  update employee_salary_records set business_id = v_biz_id where business_id is null;
  update production_batches set business_id = v_biz_id where business_id is null;
  update chart_of_accounts set business_id = v_biz_id where business_id is null;
  update journal_entries set business_id = v_biz_id where business_id is null;
  update journal_lines set business_id = v_biz_id where business_id is null;
  update cash_accounts set business_id = v_biz_id where business_id is null;
  update cash_transactions set business_id = v_biz_id where business_id is null;
  update audit_logs set business_id = v_biz_id where business_id is null;
  update notifications set business_id = v_biz_id where business_id is null;
  update suppliers set business_id = v_biz_id where business_id is null;
  update supplier_payments set business_id = v_biz_id where business_id is null;
  update purchases set business_id = v_biz_id where business_id is null;
  update purchase_items set business_id = v_biz_id where business_id is null;
  update automation_rules set business_id = v_biz_id where business_id is null;
end $$;
